# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e70a5d0a59ad00b1558cc55d4d2ca97e1e1f22f67be0e5fd4e302424bbd5d87dfa8d81cd26c9d00306674233a5504c73c94d73ff88591af00e53d0fbe5f2a2bb

test:
  secret_key_base: 4a07c5d0039bca7ed1f5b60db663adc2265ca969f206f85d10ca967be03ba7859753b5d968e9265ad77e754f508b78a3008d2b230f631c4b1271ab90b498cdcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
